---
- name: Fetch a number of drives
  become: true
  shell: |
    /opt/MegaRAID/storcli/storcli64 /call/vall show all \
      | grep 'Number of Drives Per Span' \
      | awk -F ' = ' '{ sum += $2 } END { print sum }'
  register: n_drives
  changed_when: false

- name: Fetch a state of a previous log file
  stat:
    path: "{{ megaraid_monitor_log_path }}"
  register: previous_log_file

- name: Count online drives at a previous run
  when:
    - previous_log_file.stat.exists
  shell: |
    grep -c 'Onln\s' "{{ megaraid_monitor_log_path }}"
  register: previous_n_online
  changed_when: false

- name: Set previous_n_online.stdout
  when:
    - not previous_log_file.stat.exists
  set_fact:
    previous_n_online:
      stdout: ''

- name: Count currently online drives
  become: true
  shell: |
    /opt/MegaRAID/storcli/storcli64  /call/eall/sall show all > "{{ megaraid_monitor_log_path }}"
    grep -c 'Onln\s' "{{ megaraid_monitor_log_path }}"
  register: n_online
  changed_when: false

- name: Summarize firmware states
  shell: |
    grep -e 'Onln\s' "{{ megaraid_monitor_log_path }}" \
      | sed -e 's/^.*Onln.*/ \/  {{ n_drives.stdout }}  drives  :\t/' \
      | sort \
      | uniq -c
  register: fw_states_msg
  changed_when: false

- name: Set a normal message
  when:
    - not previous_log_file.stat.exists
    - n_online.stdout == n_drives.stdout
  set_fact:
    slack_color: good
    slack_msg: "[ firmware states on {{ inventory_hostname }} ]\n{{ fw_states_msg.stdout }}"

- name: Set a warning message
  when:
    - n_online.stdout not in [ n_drives.stdout, previous_n_online.stdout ]
  set_fact:
    slack_color: danger
    slack_msg: "Disk failure was detected.\n[ firmware states on {{ inventory_hostname }} ]\n{{ fw_states_msg.stdout }}"

- name: Send a message via Slack
  when:
    - slack_color is defined
    - slack_msg is defined
  local_action:
    module: slack
    token: "{{ slack_token }}"
    msg: "{{ slack_msg }}"
    color: "{{ slack_color }}"
    channel: "#{{ slack_channel }}"
    username: "{{ ansible_user }}@{{ inventory_hostname }}"
    icon_url: "{{ slack_icon_url }}"
